export const AVATAR_API = 'https://ui-avatars.com/api'
export const API = 'https://birdfarmmeal.somee.com/api'
export const AUTH_TOKEN = 'authToken'
export const USER_INFO = 'userInfo'
export const BEARER = 'Bearer'
